HF/urls.py
from django.conf.urls import include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^', include('app.urls')),
]

app/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from .models import Post, Post_user, Comment, Comment_user, Color

CITY_LOT = (
    ('', ''),
    ('Минск', 'Минск'),
    ('Брест', 'Брест'),
    ('Могилёв', 'Могилёв'),
    ('Гомель', 'Гомель'),
    ('Гродно', 'Гродно'),
    ('Витебск', 'Витебск'),
    )

SEX = (
    [('Мужчина', 'Мужчина'),
    ('Женщина', 'Женщина')]
)

HAIR = (
    ('', ''),
    ('Брюнет', 'Брюнет'),
    ('Шатен', 'Шатен'),
    ('Рыжий', 'Рыжий'),
    ('Русый', 'Русый'),
    ('Блондин', 'Блондин'),
    ('Седой', 'Седой'),
    ('Другое', 'Другое'),
    ('Волос нет', 'Волос нет'),
    ('Неизвестно', 'Неизвестно'),
    )

BODY = (
    ('', ''),
    ('Худощавое', 'Худощавое'),
    ('Нормальное', 'Нормальное'),
    ('Полное', 'Полное'),
    ('Очень полное', 'Очень полное'),
    ('Неизвестно', 'Неизвестно'),
    )

EYES = (
    ('', ''),
    ('Синий', 'Синий'),
    ('Голубой', 'Голубой'),
    ('Серый', 'Серый'),
    ('Зелёный', 'Зелёный'),
    ('Янтарный', 'Янтарный'),
    ('Карий', 'Карий'),
    ('Другое', 'Другое'),
    ('Неизвестно', 'Неизвестно'),
    )

HAT = (
    ('', ''),
    ('Шапка мех.', 'Шапка мех.'),
    ('Кепка', 'Кепка'),
    ('Шляпа', 'Шляпа'),
    ('Шапка вяз.', 'Шапка вяз.'),
    ('Другое', 'Другое'),
    ('Отсутствует', 'Отсутствует'),
    )

VVERH = (
    ('', ''),
    ('Куртка', 'Куртка'),
    ('Пальто', 'Пальто'),
    ('Дублёнка', 'Дублёнка'),
    ('Шуба', 'Шуба'),
    ('Плащ', 'Плащ'),
    ('Другое', 'Другое'),
    ('Отсутствует', 'Отсутствует'),
    )

NIZ = (
    ('', ''),
    ('Любые', 'Любые'),
    ('Брюки', 'Брюки'),
    ('Джинсы', 'Джинсы'),
    ('Спорт. штаны', 'Спорт. штаны'),
    ('Шорты', 'Шорты'),
    ('Другое', 'Другое'),
    ('Отсутствует', 'Отсутствует'),
    )

BOOTS = (
    ('', ''),
    ('Сапоги', 'Сапоги'),
    ('Ботинки', 'Ботинки'),
    ('Туфли', 'Туфли'),
    ('Кроссовки', 'Кроссовки'),
    ('Кеды', 'Кеды'),
    ('Тапочки', 'Тапочки'),
    ('Сандали', 'Сандали'),
    ('Другое', 'Другое'),
    ('Отсутствует', 'Отсутствует'),
    )


COLORS = (
    ('', ''),
    ('Красный', 'Красный'),
    ('Синий', 'Синий'),
    ('Зелёный', 'Зелёный'),
    ('Серый', 'Серый'),
    ('Коричневый', 'Коричневый'),
    ('Чёрный', 'Чёрный'),
    ('Белый', 'Белый'),
    ('Другой', 'Другой'),
    )


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('name', 'surname', 'fam', 'city', 'text', 'gender', 'age', 'height',
                  'body', 'eyes_color', 'hair_color', 'shramy', 'tatu', 'protez', 'konech',
                  'hat', 'hat_color', 'vverh', 'vverh_color', 'niz', 'niz_color', 'boots',
                  'boots_color', 'hospital',)

    name = forms.CharField(required=False, label='name', widget=forms.TextInput(attrs={'placeholder': 'Имя'}))
    surname = forms.CharField(required=False, label='surname', widget=forms.TextInput(attrs={'placeholder': 'Фамилия'}))
    fam = forms.CharField(required=False, label='fam', widget=forms.TextInput(attrs={'placeholder': 'Отчество'}))
    age = forms.CharField(required=False, label='age', max_length='3', widget=forms.TextInput(attrs={'placeholder': 'Возраст'}))
    height = forms.CharField(required=False, label='height', max_length='3', widget=forms.TextInput(attrs={'placeholder': 'Рост'}))
    city = forms.CharField(required=False, label='city', widget=forms.Select(choices=CITY_LOT))
    body = forms.CharField(initial="Неизвестно", required=False, widget=forms.Select(choices=BODY))
    eyes_color = forms.CharField(initial="Неизвестно", required=False, widget=forms.Select(choices=EYES))
    hair_color = forms.CharField(initial="Неизвестно", required=False, widget=forms.Select(choices=HAIR))
    gender = forms.ChoiceField(choices=SEX, widget=forms.RadioSelect())

    hat = forms.CharField(initial="Отсутствует", required=False, widget=forms.Select(choices=HAT))
    vverh = forms.CharField(initial="Отсутствует", required=False, widget=forms.Select(choices=VVERH))
    niz = forms.CharField(initial="Отсутствует", required=False, widget=forms.Select(choices=NIZ))
    boots = forms.CharField(initial="Отсутствует", required=False, widget=forms.Select(choices=BOOTS))


class PostFormUser(forms.ModelForm):

    class Meta:
        model = Post_user
        fields = ('name', 'surname', 'fam', 'city', 'text', 'gender', 'age', 'height',
                  'body', 'eyes_color', 'hair_color', 'shramy', 'tatu', 'protez', 'konech',
                  'hat', 'hat_color', 'vverh', 'vverh_color', 'niz', 'niz_color', 'boots',
                  'boots_color', 'address', 'phone_number', 'image',)

    name = forms.CharField(required=False, label='name', widget=forms.TextInput(attrs={'placeholder': 'Имя'}))
    surname = forms.CharField(required=False, label='surname', widget=forms.TextInput(attrs={'placeholder': 'Фамилия'}))
    fam = forms.CharField(required=False, label='fam', widget=forms.TextInput(attrs={'placeholder': 'Отчество'}))
    age = forms.CharField(required=False, label='age', max_length='3', widget=forms.TextInput(attrs={'placeholder': 'Возраст'}))
    height = forms.CharField(required=False, label='height', max_length='3', widget=forms.TextInput(attrs={'placeholder': 'Рост'}))
    city = forms.CharField(required=False, label='city', widget=forms.Select(choices=CITY_LOT))
    body = forms.CharField(initial="Неизвестно", required=False, widget=forms.Select(choices=BODY))
    eyes_color = forms.CharField(initial="Неизвестно", required=False, widget=forms.Select(choices=EYES))
    hair_color = forms.CharField(initial="Неизвестно", required=False, widget=forms.Select(choices=HAIR))
    gender = forms.ChoiceField(choices=SEX, widget=forms.RadioSelect())
    address = forms.CharField(required=False, label='address')
    phone_number = forms.CharField(required=False, label='phone_number')
    image = forms.ImageField(required=False, label='photo')

    hat = forms.CharField(initial="Отсутствует", required=False, widget=forms.Select(choices=HAT))
    vverh = forms.CharField(initial="Отсутствует", required=False, widget=forms.Select(choices=VVERH))
    niz = forms.CharField(initial="Отсутствует", required=False, widget=forms.Select(choices=NIZ))
    boots = forms.CharField(initial="Отсутствует", required=False, widget=forms.Select(choices=BOOTS))


class SearchForm1(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('id', 'name', 'surname', 'fam','age', 'height',
                  'body', 'eyes_color', 'hair_color', 'hat', 'hat_color', 'vverh', 'vverh_color', 'niz', 'niz_color', 'boots',
                  'boots_color', 'shramy', 'tatu', 'protez', 'konech',)

    id = forms.CharField(required=False, label='id', widget=forms.TextInput(attrs={'placeholder': 'ID'}))
    name = forms.CharField(required=False, label='name', widget=forms.TextInput(attrs={'placeholder': 'Имя'}))
    surname = forms.CharField(required=False, label='surname', widget=forms.TextInput(attrs={'placeholder': 'Фамилия'}))
    fam = forms.CharField(required=False, label='fam', widget=forms.TextInput(attrs={'placeholder': 'Отчество'}))
    age = forms.CharField(required=False, label='age', max_length='3', widget=forms.TextInput(attrs={'placeholder': 'Возраст'}))
    height = forms.CharField(required=False, label='height', max_length='3', widget=forms.TextInput(attrs={'placeholder': 'Рост'}))
    body = forms.CharField(required=False, widget=forms.Select(choices=BODY))
    eyes_color = forms.CharField(required=False, widget=forms.Select(choices=EYES))
    hair_color = forms.CharField(required=False, widget=forms.Select(choices=HAIR))
    hat = forms.ChoiceField(required=False, choices=HAT)
    vverh = forms.CharField(required=False, widget=forms.Select(choices=VVERH))
    niz = forms.CharField(required=False, widget=forms.Select(choices=NIZ))
    boots = forms.CharField(required=False, widget=forms.Select(choices=BOOTS))
    shramy = forms.BooleanField(required=False)
    tatu = forms.BooleanField(required=False)
    protez = forms.BooleanField(required=False)
    konech = forms.BooleanField(required=False)

    # hat_color = forms.ModelChoiceField(queryset=Color.objects.all(), empty_label="Выберите цвет", to_field_name="color_name")
    # vverh_color = forms.ModelChoiceField(queryset=Color.objects.all(), empty_label="Выберите цвет")
    # niz_color = forms.ModelChoiceField(queryset=Color.objects.all(), empty_label="Выберите цвет")
    # boots_color = forms.ModelChoiceField(queryset=Color.objects.all(), empty_label="Выберите цвет")
    # text = forms.TextField(required=False, label='height', max_length='100')



# class SearchForm1(forms.Form):
#     id = forms.CharField(required=False, label='id', widget=forms.TextInput(attrs={'placeholder': 'ID'}))
#     name = forms.CharField(required=False, label='name', widget=forms.TextInput(attrs={'placeholder': 'Имя'}))
#     surname = forms.CharField(required=False, label='surname', widget=forms.TextInput(attrs={'placeholder': 'Фамилия'}))
#     fam = forms.CharField(required=False, label='fam', widget=forms.TextInput(attrs={'placeholder': 'Отчество'}))
#     age = forms.CharField(required=False, label='age', max_length='3', widget=forms.TextInput(attrs={'placeholder': 'Возраст'}))
#     height = forms.CharField(required=False, label='height', max_length='3', widget=forms.TextInput(attrs={'placeholder': 'Рост'}))
#     body = forms.CharField(initial="Неизвестно", required=False, widget=forms.Select(choices=BODY))
#     eyes_color = forms.CharField(initial="Неизвестно", required=False, widget=forms.Select(choices=EYES))
#     hair_color = forms.CharField(initial="Неизвестно", required=False, widget=forms.Select(choices=HAIR))
#     hat = forms.CharField(initial="Отсутствует", required=False, widget=forms.Select(choices=HAT))

app/templates/blog/map.html
{% extends 'blog/base.html' %}
{% load staticfiles %}


{% block content %}
    <script>
      function initMap() {
          var styleArray = [
              {
                  featureType: "all",
                  stylers: [
                      {saturation: -80}
                  ]
              }, {
                  featureType: "road.arterial",
                  elementType: "geometry",
                  stylers: [
                      {hue: "#3EB9F7"},
                      {saturation: 50}
                  ]
              }, {
                  featureType: "poi.business",
                  elementType: "labels",
                  stylers: [
                      {visibility: "on"}
                  ]
              }
          ];
          var myLatLng = {lat: {{ post.hospital.lat }}, lng: {{post.hospital.lng}}};
          var map = new google.maps.Map(document.getElementById('map'), {
              center: myLatLng,
              styles: styleArray,
              zoom: 17
          });
          var image = {
              url: '{% static "img/post/marker.png" %}'
          };
          var marker = new google.maps.Marker({
              map: map,
              position: myLatLng,
              icon: image,
              title: '{{ post.hospital.hospital_name }}'
          });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDy4VU470BtjNNKRHpfOGpnwrc1rvQZKmo&callback=initMap"
        async defer></script>

    <div id="map"></div>
{% endblock %}

app/templates/blog/post_edit_user.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"></div>
    <div class="content container col-lg-6 col-md-6 col-sm-6 col-xs-6">
    {% if form.errors %}
        <p id="error_login">{{ form.errors }}</p>
    {% endif %}
	<form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
        <div class="edit_form col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <p class="nov_ob">Новое объявления</p>
            <div class="FIO">
                <div style="padding: 0; text-align: center;" class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    {{ form.surname }}
                </div>
                <div style="padding: 0; text-align: center;" class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    {{ form.name }}
                </div>
                <div style="padding: 0; text-align: center;" class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    {{ form.fam }}
                </div>
            </div>
            <div class="row">
                <div class="gender">
                    {{ radio.choice_label }}
                    {% for radio in form.gender %}
                        <div class="radio{{ radio.id_for_label }}">
                            <div class="radio_label col-lg-6 col-md-6 col-sm-6 col-xs-6">{{ radio.tag }}</div>
                            <div class="radio_tag col-lg-6 col-md-6 col-sm-6 col-xs-6">{{ radio.choice_label }}</div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="edit_form1 col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <p class="opis">Описание</p>
            <div class="row age">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
                <div style="padding: 0;margin-left: 20px" class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                    {{ form.age }}
                    <p style="margin-top: 24px; font-size: 22px">лет</p>
                </div>
                <div style="padding: 0" class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                    <p style="margin-top: 24px; margin-left: 13%; font-size: 22px; float: right;">см</p>
                    {{ form.height }}

                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
            </div>
            <div class="opis_2">
                <div class="bodys">
                    <div class="row">
                        <p>Телосложения</p>
                        {{ form.body }}
                    </div>
                </div>
                <div class="hair">
                    <div class="row">
                        <p>Цвет волос</p>
                        {{ form.hair_color }}
                    </div>
                </div>
                <div class="eyes">
                    <div class="row">
                        <p>Цвет глаз</p>
                        {{ form.eyes_color }}
                    </div>
                </div>
                <div style="margin-left: 37%" class="check">
                    <div>Шрамы:<p>{{ form.shramy }}</p></div>
                    <div>Тату:<p>{{ form.tatu }}</p></div>
                    <div>Протезы:<p>{{ form.protez }}</p></div>
                    <div>Отсутвствие конечностей:<p>{{ form.konech }}</p></div>
                </div>
            </div>
        </div>
        <div class="edit_form2 col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <p class="opis">Обстоятельства обнаружения</p>
            <div class="row bodys">
                <p>Город</p>
                {{ form.city }}
            </div>
            <div class="row user_address">
                <p>Адрес</p>
                {{ form.address }}
            </div>
            <div class="row user_phone_number">
                <p>Контактные данные</p>
                {{ form.phone_number }}
            </div>
            <div class="row bodys">
                <p>Головной убор</p>
                {{ form.hat }}
            </div>
            <div class="row bodys">
                <p>Цвет головного убора</p>
                {{ form.hat_color }}
            </div>
            <div class="row bodys">
                <p>Верхняя одежда</p>
                {{ form.vverh }}
            </div>
            <div class="row bodys">
                <p>Цвет верхней одежды</p>
                {{ form.vverh_color }}
            </div>
            <div class="row bodys">
                <p>Штаны</p>
                {{ form.niz }}
            </div>
            <div class="row bodys">
                <p>Цвет штанов</p>
                {{ form.niz_color }}
            </div>
            <div class="row bodys">
                <p>Обувь</p>
                {{ form.boots }}
            </div>
            <div class="row bodys">
                <p>Цвет обуви</p>
                {{ form.boots_color }}
            </div>
            <div class="text">
                {% if form.text.value %}
                    <textarea cols="40" id="id_text" name="text" rows="10" placeholder="Описание">{{ form.text.value }}</textarea>
                {% else %}
                    <textarea cols="40" id="id_text" name="text" rows="10" placeholder="Описание">{{ form.text.placeholder }}</textarea>
                {% endif %}
            </div>
            <div class="row image_edit">
                <input id="id_image" name="image" type="file">
            </div>
            <button type="submit" class="save1 btn btn-default">Сохранить</button>
        </div>
	</form>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"></div>
{% endblock %}

app/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block content %}
    <div style="width: 350px; margin-right: 100px; margin-left: 15px" class="search col-lg-3 col-md-3 col-sm-3 col-xs-3">
        <div class="row search1">
            <form style="padding: 0" method="GET"  class="navbar-form">{% csrf_token %}
                <div class="form-group">
                    <div class="row">
                        <p class="inf">Общая информация</p>
                    </div>
                    <div class="row inf1" style="margin-bottom: 30px">
                        {{ form.id }}
                    </div>
                    <div class="row inf1">
                        {{ form.name }}
                    </div>
                    <div class="row inf1">
                        {{ form.surname }}
                    </div>
                    <div class="row inf1">
                        {{ form.fam }}
                    </div>
                    <div class="row" style="margin-bottom: 10px; padding-left: 15px; padding-right: 15px">
                        <div>{{ form.age }}</div>
                        <div>{{ form.height }}</div>
                    </div>
                    <div class="row">
                        <p class="inf">Описание</p>
                    </div>
                    <div class="row inf2">
                        Телосложение
                    </div>
                    <div class="row inf1">
                        {{ form.body }}
                    </div>
                    <div class="row inf2">
                        Цвет волос
                    </div>
                    <div class="row inf1">
                        {{ form.hair_color }}
                    </div>
                    <div class="row inf2">
                        Цвет глаз
                    </div>
                    <div class="row inf1" style="margin-bottom: 20px">
                        {{ form.eyes_color }}
                    </div>
                    <div class="row check inf2" style="margin: 0">
                        <div>Шрамы:<p>{{ form.shramy }}</p></div>
                        <div>Тату:<p>{{ form.tatu }}</p></div>
                        <div>Протезы:<p>{{ form.protez }}</p></div>
                        <div>Отсутвствие конечностей:<p>{{ form.konech }}</p></div>
                    </div>
{#                    <div class="row inf1">#}
{#                        <select title="hat" id="id_hat" name="hat">#}
{#                            {% for x, y in form.hat.field.choices %}#}
{#                                <option value="{{ x }}">{{ y }}</option>#}
{#                            {% endfor %}#}
{#                        </select>#}
{#                    </div>#}
                    <div class="row inf2">
                        Головной убор
                    </div>
                    <div class="row inf1">
                        {{ form.hat }}
                    </div>
                    <div class="row inf2">
                        Цвет головного убора
                    </div>
                    <div class="row inf1">
                        {{ form.hat_color }}
                    </div>
                    <div class="row inf2">
                        Верхняя одежда
                    </div>
                    <div class="row inf1">
                        {{ form.vverh }}
                    </div>
                    <div class="row inf2">
                        Цвет верхней одежды
                    </div>
                    <div class="row inf1">
                        {{ form.vverh_color }}
                    </div>
                    <div class="row inf2">
                        Штаны
                    </div>
                    <div class="row inf1">
                        {{ form.niz }}
                    </div>
                    <div class="row inf2">
                        Цвет штанов
                    </div>
                    <div class="row inf1">
                        {{ form.niz_color }}
                    </div>
                    <div class="row inf2">
                        Обувь
                    </div>
                    <div class="row inf1">
                        {{ form.boots }}
                    </div>
                    <div class="row inf2">
                        Цвет обуви
                    </div>
                    <div class="row inf1" style="margin-bottom: 50px">
                        {{ form.boots_color }}
                    </div>
{#                    <div class="row">#}
{#                        {{ form.text }}#}
{#                    </div>#}
                    <div class="row">
                        <button style="margin-bottom: 20px" type="submit" class="btn btn-default save3">Искать</button>
                    </div>
                </div>
            </form>
        </div>
    </div>





    <div class="content container col-lg-6 col-md-6 col-sm-6 col-xs-6">
    {% for post in posts %}
        <div class="post3 col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="post">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <a class="comments" style="float: left" href="{% url 'post_detail' pk=post.pk %}">Комментарии: {{ post.approved_comments.count }}</a>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <p style="font-size: 16">ID {{ post.pk }}</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <div class="date1">
				        <p class="date1">{{ post.published_date }}</p>
			        </div>
                </div>
            </div>
			<h1 class="FIO_post_detail1"><a href="{% url 'app.views.post_detail' pk=post.pk %}">{{ post.surname }} {{ post.name }} {{ post.fam }}</a></h1>
            <div class="row row11">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <div class="row profile1 opis_post_detail">Возраст<div class="row_age1">{{ post.age }}</div><p class="sm1">лет</p></div>
                </div>
                {% if post.gender == 'Мужчина' %}
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        <img class="Male1" src="{% static "img/post/Male.png" %}" alt="User" />
                    </div>
                {% else %}
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        <img class="Male1" src="{% static "img/post/Female.png" %}" alt="User" />
                    </div>
                {% endif %}
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <div class="row profile1 opis_post_detail">Рост<div class="row_height1">{{ post.height }}</div><p class="sm1">см</p></div>
                </div>
            </div>

            <hr class="hr_post_detail1">

            <div class="row row21">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <img class="Torso1" src="{% static "img/post/Torso.png" %}" alt="Body" />
                    <p class="profile1">{{ post.body }}</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <img class="Haircut" src="{% static "img/post/Hair.png" %}" alt="Hair" />
                    <p class="profile1">{{ post.hair_color }}</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <img class="Eye1" src="{% static "img/post/Eye.png" %}" alt="Eye" />
                    <p class="profile1">{{ post.eyes_color }}</p>
                </div>
            </div>

            <hr class="hr_post_detail1">

            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <p class="primet2">Местонахождение</p>
                </div>
            </div>
            <div class="row row6">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <p class="hospital_name">{{ post.hospital.hospital_name }}</p>
                </div>
            </div>
            <div class="row row71">
                <div class="adress col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <p class="address1">{{ post.hospital.hospital_adress }}</p>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <p class="number1">{{ post.hospital.hospital_number1 }}</p>
                </div>
            </div>
		</div>
        </div>
	{% endfor %}

    {% if posts %}
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 columns">
                <ul class="pagination">
                    {% if posts.has_previous %}
                        <li class="arrow"><a href="/page/{{ posts.previous_page_number }}/">&laquo;</a></li>
                    {% else %}
                        <li class="arrow disabled"><a>&laquo;</a></li>
                    {% endif %}
                    {% for page in posts.paginator.page_range %}
                        {% if page == posts.number %}
                            <li class="current"><a href="/page/{{ page }}/">{{ page }}</a></li>
                        {% else %}
                            <li><a href="/page/{{ page }}/">{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if posts.has_next %}
                        <li class="arrow"><a href="/page/{{ posts.next_page_number }}/">&raquo;</a></li>
                    {% else %}
                        <li class="arrow disabled"><a>&raquo;</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    {% endif %}
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"></div>
{% endblock content %}

app/templates/blog/user_profile.html
{% extends 'base.html' %}


{% block content %}
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"></div>
    <div class="content container col-lg-6 col-md-6 col-sm-6 col-xs-6">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                <form class="form-horizontal" method="post" action="{% url 'user_profile' %}">
                {% csrf_token %}
                    <div class="form-group login_group">
                        <div class="">
                            {{ form.first_name.errors }}
                            {{ form.first_name.label_tag }} <input type="text" class="form-control" id="id_first_name" name="first_name" >
                        </div>
                    </div>
                    <div class="form-group login_group">
                        <div class="">
                            {{ form.last_name.errors }}
                            {{ form.last_name.label_tag }} <input type="text" class="form-control" id="id_last_name" name="last_name" >
                        </div>
                    </div>
                    <div class="form-group login_group">
                        <div class="col-sm-offset-2" id="div_btn_login">
                            <button type="submit" class="btn btn-primary" value="save" id="btn_login">Сохранить</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></div>
        </div>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"></div>

{% endblock %}